/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Anyeli Caraanza R
 */
public class GUIIntrucciones extends javax.swing.JFrame {

    /**
     * Creates new form GUIIntrucciones
     */
    public GUIIntrucciones() {
        initComponents();
        
    }
    
    public void escuchar (ActionListener controlador){
        botonsalirdeinstrucciones.addActionListener(controlador);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonsalirdeinstrucciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonsalirdeinstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonsalirbueno.jpg"))); // NOI18N
        botonsalirdeinstrucciones.setActionCommand("salirinstrucciones");
        botonsalirdeinstrucciones.setBorderPainted(false);
        botonsalirdeinstrucciones.setContentAreaFilled(false);
        getContentPane().add(botonsalirdeinstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INTRUCCIONES .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonsalirdeinstrucciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
