/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;

/**
 *
 * @author Anyeli Caraanza R
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents();
        escuchar (controlador);
    }
    public void escuchar (ControladorPrincipal controlador){
        
        botoninstrucciones.addActionListener(controlador);
        botonhistoria.addActionListener(controlador);
        botonjugar.addActionListener(controlador);
        botonsalir.addActionListener(controlador);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoninstrucciones = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        botonhistoria = new javax.swing.JButton();
        botonjugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botoninstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoninsinstruccionesbueno.jpg"))); // NOI18N
        botoninstrucciones.setActionCommand("instrucciones");
        botoninstrucciones.setContentAreaFilled(false);
        botoninstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoninstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(botoninstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 280, 110));

        botonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonsalirbueno.jpg"))); // NOI18N
        botonsalir.setActionCommand("salir");
        botonsalir.setContentAreaFilled(false);
        getContentPane().add(botonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 440, -1, -1));

        botonhistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botoninshistoriabueno.jpg"))); // NOI18N
        botonhistoria.setActionCommand("historia");
        botonhistoria.setContentAreaFilled(false);
        getContentPane().add(botonhistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, -1, -1));

        botonjugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/botonjugarbueno.jpg"))); // NOI18N
        botonjugar.setActionCommand("jugar");
        botonjugar.setContentAreaFilled(false);
        getContentPane().add(botonjugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BIENVENIDA.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -20, 1200, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoninstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoninstruccionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botoninstruccionesActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonhistoria;
    private javax.swing.JButton botoninstrucciones;
    private javax.swing.JButton botonjugar;
    private javax.swing.JButton botonsalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
